<?php
$phrases = [
    "tenant rights",
    "renters rights",
    "Tenant Eviction",
    "illegal eviction",
    "constructive eviction",
    "tenant rights los angeles",
    "renters rights los angeles",
    "tenant rights LA",
    "renters rights LA",
    "constructive eviction LA",
    "constructive eviction los angeles",
    "tenant rights los angeles california",
    "renters rights los angeles california",
    "tenant rights LA california", 
    "renters rights LA california", 
    "Homelessness", 
    "Affordable housing",
    "Low income tenants", 
    "Rent control Tenant",
    "Rent control retners",
    "Slumlords", 
    "Landlord Harassment",
];